language: haskell

before_install:
    - |
      bash <(curl -sS https://nixos.org/nix/install)
      source $HOME/.nix-profile/etc/profile.d/nix.sh
      nix-channel --update

install:
    - nix-shell --command 'cabal test'

script: true
    # TODO
    # - cabal install --enable-tests
    # - cabal install examples/
